/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-07-31 at 20:50:19 UTC 
 * Modify at your own risk.
 */

package it.fdev.unisaconnect.model.bustrattaendpoint.model;

/**
 * Model definition for BusFermata.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the bustrattaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BusFermata extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private BusCorsa corsa;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer ora;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer posizione;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String stazione;

  /**
   * @return value or {@code null} for none
   */
  public BusCorsa getCorsa() {
    return corsa;
  }

  /**
   * @param corsa corsa or {@code null} for none
   */
  public BusFermata setCorsa(BusCorsa corsa) {
    this.corsa = corsa;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public BusFermata setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getOra() {
    return ora;
  }

  /**
   * @param ora ora or {@code null} for none
   */
  public BusFermata setOra(java.lang.Integer ora) {
    this.ora = ora;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPosizione() {
    return posizione;
  }

  /**
   * @param posizione posizione or {@code null} for none
   */
  public BusFermata setPosizione(java.lang.Integer posizione) {
    this.posizione = posizione;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStazione() {
    return stazione;
  }

  /**
   * @param stazione stazione or {@code null} for none
   */
  public BusFermata setStazione(java.lang.String stazione) {
    this.stazione = stazione;
    return this;
  }

  @Override
  public BusFermata set(String fieldName, Object value) {
    return (BusFermata) super.set(fieldName, value);
  }

  @Override
  public BusFermata clone() {
    return (BusFermata) super.clone();
  }

}
